name: 步步宝
on:
  workflow_dispatch:
  schedule:
    - cron: '0,30 0-23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
      
      - name: Checkout
        run: |
          git clone git@github.com:dkchen2008/JavaScript.git.git ~/JavaScript
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          cd ~/JavaScript
          npm install
          npm install cron
          npm install request
          curl ipinfo.io/json
      - name: '【步步宝】'
        run: |
          cd ~/JavaScript
          node Task/bububao.js
