name: yuedongzu@ziye3
on:
  workflow_dispatch:
  watch:
    types: started
  schedule:
    - cron: '0,30 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
      
      
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
          npm install cron
          npm install request
      
      - name: '【悦动组】'
        run: |
          node Task/yuedongzu.js
 
